document.querySelector('body').insertAdjacentHTML('afterbegin','<header><nav class="navbar navbar-expand-lg navbar-light"><div class="container"><a class="navbar-brand" href="https://wsoft.ws/"><img src="https://wsoft.ws/favicon.svg" alt="WSOFT"  width="30" class="d-inline-block align-text-top" style="width:initial;" />&nbsp;WSOFT</a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav-navbar" aria-controls="nav-navbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="nav-navbar"><ul class="navbar-nav me-auto mb-2 mb-lg-0"><li class="nav-item"><a id="nav-home" class="nav-link" aria-current="page" href="https://wsoft.ws/">Home</a></li><li class="nav-item"><a id="nav-about" class="nav-link" href="https://wsoft.ws/About">About</a></li><li class="nav-item"><a id="nav-works" class="nav-link" href="https://wsoft.ws/Works">Works</a></li><li class="nav-item"><a id="nav-docs" class="nav-link" aria-current="page" href="https://docs.wsoft.ws/">Docs</a></li><li class="nav-download"><a id="nav-downloads" class="nav-link" href="https://download.wsoft.ws">Download</a></li><li class="nav-contact"><a id="nav-contact" class="nav-link" href="https://wsoft.ws/Contact">Contact</a></li></ul><a class="navbar-text" href="https://github.com/WSOFT-Project"><i class="bi bi-github"></i></a><span class="navbar-text">&nbsp;&nbsp;</span><a class="navbar-text" href="https://twitter.com/WSOFT7"><i class="bi bi-twitter"></i></a><span class="navbar-text">&nbsp;&nbsp;</span><a class="navbar-text" href="https://a.wsoft.ws/discord"><i class="bi bi-discord"></i></a><span class="navbar-text">&nbsp;&nbsp;</span><a class="navbar-text" href="https://a.wsoft.ws/youtube"><i class="bi bi-youtube"></i></a></div></div></nav></header>');
document.querySelector('body').insertAdjacentHTML('beforeend', '<footer class="border-top footer text-muted .position-absolute.bottom-0.start-50.translate-middle-x" style="padding-top: 15px;"><div class="container"><div class="row"><div class="col-md"><p>Copyright &copy; 2017 WSOFT All Rights Reserved.</p></div><div class="col-md"><p class=""><a href="https://docs.wsoft.ws/legal" id="legal-link" class="text-decoration-none text-muted">法的資料</a>&nbsp;|&nbsp;<a href="https://stats.uptimerobot.com/3XOGPIXk0p" class="text-decoration-none text-muted">サービス状況</a>&nbsp;|&nbsp;<a href="https://wsoft.ws/Sitemap" class="text-decoration-none text-muted">サイトマップ</a></p></div><div class="col-md-1"><a data-bs-toggle="modal" data-bs-target="#wsoft-custom-modal"><img class="fit-picture" src="https://wsoft.ws/WS-Emblem.png" style="width : 30px" alt="Powerd by WSOFT"></a></div></div></div></footer>');
function setLegalLink(url) {
    document.getElementById('legal-link').setAttribute('href', url);
}
function setLegalLink(url,text) {
    let a=document.getElementById('legal-link');
    a.setAttribute('href', url);
    a.innerHTML=text;
}
